#!/usr/bin/env bash

# The stub writers below emit literal shell source into fixture scripts;
# unexpanded single-quoted parameters are the point.
# shellcheck disable=SC2016

set -euo pipefail

REPOSITORY_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SCRIPT_PATH="$REPOSITORY_ROOT/scripts/prepare-release.sh"
TEST_ROOT="$(mktemp -d "${TMPDIR:-/tmp}/xc-prepare-release-tests.XXXXXX")"
TEST_FAILURES=0

trap 'rm -rf "$TEST_ROOT"' EXIT

fail() {
    printf '    %s\n' "$1" >&2
    return 1
}

assert_equal() {
    local expected="$1"
    local actual="$2"
    local message="$3"

    if [[ "$actual" != "$expected" ]]; then
        fail "$message (expected '$expected', got '$actual')"
    fi
}

assert_contains() {
    local value="$1"
    local expected_substring="$2"
    local message="$3"

    if [[ "$value" != *"$expected_substring"* ]]; then
        fail "$message (missing '$expected_substring')"
    fi
}

assert_ref_exists() {
    local repository="$1"
    local ref="$2"
    local message="$3"

    if ! git -C "$repository" show-ref --verify --quiet "$ref"; then
        fail "$message (missing '$ref')"
    fi
}

assert_ref_absent() {
    local repository="$1"
    local ref="$2"
    local message="$3"

    if git -C "$repository" show-ref --verify --quiet "$ref"; then
        fail "$message (unexpected '$ref')"
    fi
}

write_swift_stub() {
    local path="$1"

    printf '%s\n' \
        '#!/usr/bin/env bash' \
        'set -euo pipefail' \
        'release_type=""' \
        'while (( $# > 0 )); do' \
        '    if [[ "$1" == "--bump" ]]; then' \
        '        release_type="$2"' \
        '        break' \
        '    fi' \
        '    shift' \
        'done' \
        'if [[ "${SWIFT_TEST_MODE:-}" == "malformed" ]]; then' \
        '    printf "not-a-version\n"' \
        '    exit 0' \
        'fi' \
        'current_version="$(sed -nE '"'"'s/.*static let number = "([0-9]+)\.([0-9]+)\.([0-9]+)".*/\1 \2 \3/p'"'"' Sources/xc/Version.swift)"' \
        'read -r major minor patch <<< "$current_version"' \
        'case "$release_type" in' \
        '    patch) patch=$((patch + 1)) ;;' \
        '    minor) minor=$((minor + 1)); patch=0 ;;' \
        '    major) major=$((major + 1)); minor=0; patch=0 ;;' \
        '    *) exit 64 ;;' \
        'esac' \
        'new_version="$major.$minor.$patch"' \
        'printf '"'"'// This file was generated by the `VersionFile` package plugin.\n\nenum Version {\n    static let number = "%s"\n}\n'"'"' "$new_version" > Sources/xc/Version.swift' \
        'if [[ "${SWIFT_TEST_MODE:-}" == "extra-change" ]]; then' \
        '    printf "unexpected\n" > Unexpected.txt' \
        'fi' \
        'if [[ "${SWIFT_TEST_MODE:-}" == "whitespace-error" ]]; then' \
        '    printf "    \n" >> Sources/xc/Version.swift' \
        'fi' \
        'printf "%s\n" "$new_version"' \
        > "$path"
}

write_gh_stub() {
    local path="$1"

    printf '%s\n' \
        '#!/usr/bin/env bash' \
        'set -euo pipefail' \
        'if [[ "$1" == "auth" && "$2" == "status" ]]; then' \
        '    exit 0' \
        'fi' \
        'if [[ "$1" == "pr" && "$2" == "list" ]]; then' \
        '    open_pr_url="${GH_TEST_OPEN_PR_URL:-}"' \
        '    is_cross_repository="${GH_TEST_OPEN_PR_IS_CROSS_REPOSITORY:-0}"' \
        '    if [[ -s "$GH_TEST_PR_STATE" ]]; then' \
        '        open_pr_url="$(sed -n "1p" "$GH_TEST_PR_STATE")"' \
        '        is_cross_repository="$(sed -n "2p" "$GH_TEST_PR_STATE")"' \
        '    fi' \
        '    json_fields=""' \
        '    jq_expression=""' \
        '    while (( $# > 0 )); do' \
        '        case "$1" in' \
        '            --json) json_fields="$2"; shift 2 ;;' \
        '            --jq) jq_expression="$2"; shift 2 ;;' \
        '            *) shift ;;' \
        '        esac' \
        '    done' \
        '    if [[ "$is_cross_repository" == "1" && "$json_fields" == *"isCrossRepository"* && "$jq_expression" == *"isCrossRepository == false"* ]]; then' \
        '        exit 0' \
        '    fi' \
        '    printf "%s" "$open_pr_url"' \
        '    exit 0' \
        'fi' \
        'if [[ "$1" == "pr" && "$2" == "create" ]]; then' \
        '    printf "%s\n" "$@" > "$GH_TEST_LOG"' \
        '    if [[ -n "${GH_TEST_CREATE_SIDE_EFFECT_URL:-}" ]]; then' \
        '        printf "%s\n%s\n" "$GH_TEST_CREATE_SIDE_EFFECT_URL" "${GH_TEST_CREATE_SIDE_EFFECT_IS_CROSS_REPOSITORY:-0}" > "$GH_TEST_PR_STATE"' \
        '    fi' \
        '    if [[ "${GH_TEST_CREATE_FAIL:-}" == "1" ]]; then' \
        '        printf "simulated PR failure\n" >&2' \
        '        exit 1' \
        '    fi' \
        '    printf "https://github.com/mgacy/swift-xc/pull/999\n"' \
        '    exit 0' \
        'fi' \
        'if [[ "$1" == "pr" && "$2" == "edit" ]]; then' \
        '    printf "%s\n" "$@" > "$GH_TEST_EDIT_LOG"' \
        '    if [[ "${GH_TEST_EDIT_FAIL:-}" == "1" ]]; then' \
        '        printf "simulated PR edit failure\n" >&2' \
        '        exit 1' \
        '    fi' \
        '    exit 0' \
        'fi' \
        'printf "unexpected gh invocation: %s\n" "$*" >&2' \
        'exit 1' \
        > "$path"
}

create_fixture() {
    local name="$1"

    FIXTURE_ROOT="$TEST_ROOT/$name"
    FIXTURE_ORIGIN="$FIXTURE_ROOT/origin.git"
    FIXTURE_WORKTREE="$FIXTURE_ROOT/worktree"
    FIXTURE_BIN="$FIXTURE_ROOT/bin"
    FIXTURE_GH_LOG="$FIXTURE_ROOT/gh.log"
    FIXTURE_GH_EDIT_LOG="$FIXTURE_ROOT/gh-edit.log"
    FIXTURE_PR_STATE="$FIXTURE_ROOT/pr-state"
    FIXTURE_OUTPUT="$FIXTURE_ROOT/output.log"
    GH_OPEN_PR_IS_CROSS_REPOSITORY="0"
    GH_CREATE_SIDE_EFFECT_URL=""
    GH_CREATE_SIDE_EFFECT_IS_CROSS_REPOSITORY="0"
    GH_EDIT_FAIL="0"

    mkdir -p "$FIXTURE_BIN"
    git init --bare --quiet "$FIXTURE_ORIGIN"
    git init --quiet --initial-branch=main "$FIXTURE_WORKTREE"
    git -C "$FIXTURE_ORIGIN" symbolic-ref HEAD refs/heads/main
    git -C "$FIXTURE_WORKTREE" config user.name "Release Script Tests"
    git -C "$FIXTURE_WORKTREE" config user.email "release-tests@example.com"
    git -C "$FIXTURE_WORKTREE" config commit.gpgsign false
    git -C "$FIXTURE_WORKTREE" remote add origin "$FIXTURE_ORIGIN"

    mkdir -p "$FIXTURE_WORKTREE/Sources/xc"
    printf '%s\n' \
        '// This file was generated by the `VersionFile` package plugin.' \
        '' \
        'enum Version {' \
        '    static let number = "0.0.1"' \
        '}' \
        > "$FIXTURE_WORKTREE/Sources/xc/Version.swift"
    printf '// fixture\n' > "$FIXTURE_WORKTREE/Package.swift"

    git -C "$FIXTURE_WORKTREE" add Package.swift Sources/xc/Version.swift
    git -C "$FIXTURE_WORKTREE" commit --quiet -m "Initial"
    git -C "$FIXTURE_WORKTREE" push --quiet -u origin main

    write_swift_stub "$FIXTURE_BIN/swift"
    write_gh_stub "$FIXTURE_BIN/gh"
    chmod +x "$FIXTURE_BIN/swift" "$FIXTURE_BIN/gh"
}

run_script() {
    local swift_mode="$1"
    local open_pr_url="$2"
    local create_pr_fails="$3"
    shift 3

    set +e
    (
        cd "$FIXTURE_WORKTREE"
        env \
            PATH="$FIXTURE_BIN:$PATH" \
            SWIFT_TEST_MODE="$swift_mode" \
            GH_TEST_OPEN_PR_URL="$open_pr_url" \
            GH_TEST_OPEN_PR_IS_CROSS_REPOSITORY="$GH_OPEN_PR_IS_CROSS_REPOSITORY" \
            GH_TEST_CREATE_FAIL="$create_pr_fails" \
            GH_TEST_LOG="$FIXTURE_GH_LOG" \
            GH_TEST_EDIT_LOG="$FIXTURE_GH_EDIT_LOG" \
            GH_TEST_PR_STATE="$FIXTURE_PR_STATE" \
            GH_TEST_CREATE_SIDE_EFFECT_URL="$GH_CREATE_SIDE_EFFECT_URL" \
            GH_TEST_CREATE_SIDE_EFFECT_IS_CROSS_REPOSITORY="$GH_CREATE_SIDE_EFFECT_IS_CROSS_REPOSITORY" \
            GH_TEST_EDIT_FAIL="$GH_EDIT_FAIL" \
            "$SCRIPT_PATH" "$@"
    ) > "$FIXTURE_OUTPUT" 2>&1
    LAST_STATUS=$?
    set -e
    LAST_OUTPUT="$(<"$FIXTURE_OUTPUT")"
}

test_happy_path() {
    create_fixture happy-path
    run_script "" "" "0" patch

    assert_equal "0" "$LAST_STATUS" "happy path should succeed" || return 1
    assert_equal "main" "$(git -C "$FIXTURE_WORKTREE" branch --show-current)" "script should return to main" || return 1
    assert_ref_exists "$FIXTURE_WORKTREE" refs/remotes/origin/release "release should be pushed" || return 1
    assert_equal \
        "Bump Version.swift -> 0.0.2" \
        "$(git -C "$FIXTURE_WORKTREE" log -1 --format=%s refs/remotes/origin/release)" \
        "release commit subject should contain the new version" || return 1
    assert_equal \
        "Sources/xc/Version.swift" \
        "$(git -C "$FIXTURE_WORKTREE" diff-tree --no-commit-id --name-only -r refs/remotes/origin/release)" \
        "release commit should change only Version.swift" || return 1
    assert_contains \
        "$(git -C "$FIXTURE_WORKTREE" show refs/remotes/origin/release:Sources/xc/Version.swift)" \
        'static let number = "0.0.2"' \
        "release branch should contain the bumped version" || return 1

    local expected_gh_arguments
    expected_gh_arguments="$(printf '%s\n' \
        pr create \
        --base main \
        --head release \
        --title '[CI] Prepare Version 0.0.2 Release' \
        --body 'Update `Version.swift` with bumped version number.' \
        --label ci)"
    assert_equal \
        "$expected_gh_arguments" \
        "$(<"$FIXTURE_GH_LOG")" \
        "PR creation should use the release contract arguments" || return 1
}

test_invalid_release_type() {
    create_fixture invalid-release-type
    run_script "" "" "0" prerelease

    if [[ "$LAST_STATUS" -eq 0 ]]; then
        fail "invalid release type should fail" || return 1
    fi
    assert_contains "$LAST_OUTPUT" "patch|minor|major" "failure should show accepted release types" || return 1
    assert_equal "main" "$(git -C "$FIXTURE_WORKTREE" branch --show-current)" "validation should not create a branch" || return 1
    assert_ref_absent "$FIXTURE_WORKTREE" refs/remotes/origin/release "validation should not push release" || return 1
}

test_dirty_worktree() {
    create_fixture dirty-worktree
    printf 'dirty\n' > "$FIXTURE_WORKTREE/README.md"
    run_script "" "" "0" patch

    if [[ "$LAST_STATUS" -eq 0 ]]; then
        fail "dirty worktree should fail" || return 1
    fi
    assert_contains "$LAST_OUTPUT" "clean worktree" "failure should explain the clean-worktree precondition" || return 1
    assert_equal "main" "$(git -C "$FIXTURE_WORKTREE" branch --show-current)" "dirty preflight should not create a branch" || return 1
}

test_wrong_branch() {
    create_fixture wrong-branch
    git -C "$FIXTURE_WORKTREE" switch --quiet -c topic
    run_script "" "" "0" patch

    if [[ "$LAST_STATUS" -eq 0 ]]; then
        fail "non-main branch should fail" || return 1
    fi
    assert_contains "$LAST_OUTPUT" "must run from main" "failure should identify the main-branch precondition" || return 1
    assert_equal "topic" "$(git -C "$FIXTURE_WORKTREE" branch --show-current)" "branch preflight should preserve the current branch" || return 1
    assert_ref_absent "$FIXTURE_WORKTREE" refs/remotes/origin/release "wrong branch should not push release" || return 1
}

test_stale_main() {
    create_fixture stale-main

    local updater="$FIXTURE_ROOT/updater"
    git clone --quiet "$FIXTURE_ORIGIN" "$updater"
    git -C "$updater" config user.name "Release Script Tests"
    git -C "$updater" config user.email "release-tests@example.com"
    git -C "$updater" config commit.gpgsign false
    printf 'upstream\n' > "$updater/Upstream.txt"
    git -C "$updater" add Upstream.txt
    git -C "$updater" commit --quiet -m "Advance main"
    git -C "$updater" push --quiet origin main

    run_script "" "" "0" patch

    if [[ "$LAST_STATUS" -eq 0 ]]; then
        fail "stale main should fail" || return 1
    fi
    assert_contains "$LAST_OUTPUT" "exactly match origin/main" "failure should identify stale main" || return 1
    assert_equal "main" "$(git -C "$FIXTURE_WORKTREE" branch --show-current)" "stale-main preflight should not create a branch" || return 1
    assert_ref_absent "$FIXTURE_WORKTREE" refs/remotes/origin/release "stale main should not push release" || return 1
}

test_existing_remote_release_branch() {
    create_fixture existing-release
    git -C "$FIXTURE_WORKTREE" branch release
    git -C "$FIXTURE_WORKTREE" push --quiet origin release
    run_script "" "" "0" patch

    if [[ "$LAST_STATUS" -eq 0 ]]; then
        fail "existing remote release branch should fail" || return 1
    fi
    assert_contains "$LAST_OUTPUT" "remote release branch already exists" "failure should identify the conflicting branch" || return 1
    assert_equal "main" "$(git -C "$FIXTURE_WORKTREE" branch --show-current)" "branch conflict should not leave main" || return 1
}

test_unmerged_local_release_branch() {
    create_fixture unmerged-local-release
    git -C "$FIXTURE_WORKTREE" switch --quiet -c release
    printf 'release\n' > "$FIXTURE_WORKTREE/Release.txt"
    git -C "$FIXTURE_WORKTREE" add Release.txt
    git -C "$FIXTURE_WORKTREE" commit --quiet -m "Unmerged release work"
    git -C "$FIXTURE_WORKTREE" switch --quiet main
    run_script "" "" "0" patch

    if [[ "$LAST_STATUS" -eq 0 ]]; then
        fail "unmerged local release branch should fail" || return 1
    fi
    assert_contains "$LAST_OUTPUT" "not merged into origin/main" "failure should protect unmerged local release work" || return 1
    assert_ref_exists "$FIXTURE_WORKTREE" refs/heads/release "unmerged local release branch should be preserved" || return 1
    assert_ref_absent "$FIXTURE_WORKTREE" refs/remotes/origin/release "unmerged local release branch should not be pushed" || return 1
}

test_existing_release_pr() {
    create_fixture existing-pr
    run_script "" "https://github.com/mgacy/swift-xc/pull/123" "0" patch

    if [[ "$LAST_STATUS" -eq 0 ]]; then
        fail "existing release PR should fail" || return 1
    fi
    assert_contains "$LAST_OUTPUT" "pull/123" "failure should report the existing PR" || return 1
    assert_equal "main" "$(git -C "$FIXTURE_WORKTREE" branch --show-current)" "PR conflict should not leave main" || return 1
}

test_fork_release_pr_does_not_block_release() {
    create_fixture fork-release-pr
    GH_OPEN_PR_IS_CROSS_REPOSITORY="1"
    run_script "" "https://github.com/mgacy/swift-xc/pull/124" "0" patch

    assert_equal "0" "$LAST_STATUS" "a fork PR whose head is named release should not block release preparation" || return 1
    assert_equal "main" "$(git -C "$FIXTURE_WORKTREE" branch --show-current)" "successful preparation should return to main" || return 1
    assert_ref_exists "$FIXTURE_WORKTREE" refs/remotes/origin/release "the same-repository release branch should be pushed" || return 1
}

test_malformed_plugin_output() {
    create_fixture malformed-output
    run_script "malformed" "" "0" patch

    if [[ "$LAST_STATUS" -eq 0 ]]; then
        fail "malformed plugin output should fail" || return 1
    fi
    assert_contains "$LAST_OUTPUT" "unexpected version" "failure should identify malformed plugin output" || return 1
    assert_ref_absent "$FIXTURE_WORKTREE" refs/remotes/origin/release "malformed output should not push release" || return 1
}

test_unexpected_changed_file() {
    create_fixture unexpected-change
    run_script "extra-change" "" "0" patch

    if [[ "$LAST_STATUS" -eq 0 ]]; then
        fail "unexpected changed file should fail" || return 1
    fi
    assert_contains "$LAST_OUTPUT" "only Sources/xc/Version.swift" "failure should identify the allowed diff" || return 1
    assert_ref_absent "$FIXTURE_WORKTREE" refs/remotes/origin/release "unexpected change should not push release" || return 1
}

test_whitespace_error_preserves_local_release() {
    create_fixture whitespace-error
    run_script "whitespace-error" "" "0" patch

    if [[ "$LAST_STATUS" -eq 0 ]]; then
        fail "whitespace errors should fail before commit" || return 1
    fi
    assert_equal "release" "$(git -C "$FIXTURE_WORKTREE" branch --show-current)" "whitespace failure should preserve the local release branch" || return 1
    assert_ref_absent "$FIXTURE_WORKTREE" refs/remotes/origin/release "whitespace failure should not push release" || return 1
    assert_contains \
        "$LAST_OUTPUT" \
        "version bump introduced whitespace errors; the local release branch was preserved" \
        "whitespace failure should explain the preserved branch state" || return 1
}

test_push_failure_preserves_local_release() {
    create_fixture push-failure

    printf '%s\n' \
        '#!/usr/bin/env bash' \
        'while read -r old_value new_value ref_name; do' \
        '    if [[ "$ref_name" == "refs/heads/release" ]]; then' \
        '        printf "release pushes rejected for test\n" >&2' \
        '        exit 1' \
        '    fi' \
        'done' \
        'exit 0' \
        > "$FIXTURE_ORIGIN/hooks/pre-receive"
    chmod +x "$FIXTURE_ORIGIN/hooks/pre-receive"

    run_script "" "" "0" patch

    if [[ "$LAST_STATUS" -eq 0 ]]; then
        fail "push rejection should fail" || return 1
    fi
    assert_equal "release" "$(git -C "$FIXTURE_WORKTREE" branch --show-current)" "push failure should preserve the local release branch" || return 1
    assert_ref_absent "$FIXTURE_WORKTREE" refs/remotes/origin/release "push failure should not create the remote release branch" || return 1
    assert_contains "$LAST_OUTPUT" "push failed" "push failure should explain that the local commit was preserved" || return 1
}

test_pre_commit_hook_cannot_expand_release_commit() {
    create_fixture pre-commit-hook

    printf '%s\n' \
        '#!/usr/bin/env bash' \
        'printf "hook change\n" > Hook.txt' \
        'git add Hook.txt' \
        > "$FIXTURE_WORKTREE/.git/hooks/pre-commit"
    chmod +x "$FIXTURE_WORKTREE/.git/hooks/pre-commit"

    run_script "" "" "0" patch

    if [[ "$LAST_STATUS" -eq 0 ]]; then
        fail "pre-commit hook expansion should fail before push" || return 1
    fi
    assert_equal "release" "$(git -C "$FIXTURE_WORKTREE" branch --show-current)" "hook failure should preserve the local release commit" || return 1
    assert_ref_absent "$FIXTURE_WORKTREE" refs/remotes/origin/release "hook-expanded commit should not be pushed" || return 1
    assert_contains "$LAST_OUTPUT" "release commit must contain only" "failure should identify the committed-tree violation" || return 1
}

test_pr_failure_preserves_pushed_release() {
    create_fixture pr-failure
    run_script "" "" "1" minor

    if [[ "$LAST_STATUS" -eq 0 ]]; then
        fail "PR creation failure should fail" || return 1
    fi
    assert_equal "release" "$(git -C "$FIXTURE_WORKTREE" branch --show-current)" "PR failure should preserve the local release branch" || return 1
    assert_ref_exists "$FIXTURE_WORKTREE" refs/remotes/origin/release "PR failure should preserve the pushed branch" || return 1
    assert_contains "$LAST_OUTPUT" "gh pr create" "PR failure should print a recovery command" || return 1
}

test_pr_failure_reconciles_created_pr() {
    create_fixture pr-created-despite-failure
    GH_CREATE_SIDE_EFFECT_URL="https://github.com/mgacy/swift-xc/pull/456"
    run_script "" "" "1" minor

    assert_equal "0" "$LAST_STATUS" "existing PR reconciliation should recover the command" || return 1
    assert_equal "main" "$(git -C "$FIXTURE_WORKTREE" branch --show-current)" "reconciled PR should return to main" || return 1
    assert_ref_exists "$FIXTURE_WORKTREE" refs/remotes/origin/release "reconciled PR should retain the pushed branch" || return 1
    assert_equal \
        "$(printf '%s\n' pr edit https://github.com/mgacy/swift-xc/pull/456 --add-label ci)" \
        "$(<"$FIXTURE_GH_EDIT_LOG")" \
        "reconciliation should ensure the ci label" || return 1
    assert_contains "$LAST_OUTPUT" "pull/456" "success should report the reconciled PR" || return 1
}

test_fork_release_pr_does_not_reconcile_failed_creation() {
    create_fixture fork-pr-created-despite-failure
    GH_CREATE_SIDE_EFFECT_URL="https://github.com/mgacy/swift-xc/pull/457"
    GH_CREATE_SIDE_EFFECT_IS_CROSS_REPOSITORY="1"
    run_script "" "" "1" minor

    if [[ "$LAST_STATUS" -eq 0 ]]; then
        fail "a fork PR whose head is named release must not reconcile a failed same-repository PR creation" || return 1
    fi
    assert_equal "release" "$(git -C "$FIXTURE_WORKTREE" branch --show-current)" "failed creation should preserve the local release branch" || return 1
    assert_ref_exists "$FIXTURE_WORKTREE" refs/remotes/origin/release "failed creation should preserve the pushed release branch" || return 1
    assert_contains "$LAST_OUTPUT" "gh pr create" "failed creation should print same-repository recovery" || return 1
    if [[ -e "$FIXTURE_GH_EDIT_LOG" ]]; then
        fail "a fork PR must not be edited during reconciliation" || return 1
    fi
}

test_pr_reconciliation_prints_edit_recovery() {
    create_fixture pr-edit-failure
    GH_CREATE_SIDE_EFFECT_URL="https://github.com/mgacy/swift-xc/pull/789"
    GH_EDIT_FAIL="1"
    run_script "" "" "1" major

    if [[ "$LAST_STATUS" -eq 0 ]]; then
        fail "failed PR metadata reconciliation should fail" || return 1
    fi
    assert_equal "release" "$(git -C "$FIXTURE_WORKTREE" branch --show-current)" "edit failure should preserve the local release branch" || return 1
    assert_contains \
        "$LAST_OUTPUT" \
        "gh pr edit https://github.com/mgacy/swift-xc/pull/789 --add-label ci" \
        "edit failure should print metadata recovery" || return 1
}

run_test() {
    local name="$1"
    local function_name="$2"

    printf '• %s\n' "$name"
    if "$function_name"; then
        printf '  PASS\n'
    else
        printf '  FAIL\n'
        TEST_FAILURES=$((TEST_FAILURES + 1))
    fi
}

run_test "creates, pushes, and opens a release PR" test_happy_path
run_test "rejects invalid release types before mutation" test_invalid_release_type
run_test "rejects a dirty worktree before mutation" test_dirty_worktree
run_test "rejects invocation outside main" test_wrong_branch
run_test "rejects stale main before mutation" test_stale_main
run_test "rejects an existing remote release branch" test_existing_remote_release_branch
run_test "preserves an unmerged local release branch" test_unmerged_local_release_branch
run_test "rejects an existing release PR" test_existing_release_pr
run_test "ignores a fork PR whose head branch is named release" test_fork_release_pr_does_not_block_release
run_test "rejects malformed version-plugin output" test_malformed_plugin_output
run_test "rejects changes outside Version.swift" test_unexpected_changed_file
run_test "preserves the local branch when the version diff has whitespace errors" test_whitespace_error_preserves_local_release
run_test "preserves the local commit when push fails" test_push_failure_preserves_local_release
run_test "rejects pre-commit hooks that expand the release commit" test_pre_commit_hook_cannot_expand_release_commit
run_test "preserves the pushed branch when PR creation fails" test_pr_failure_preserves_pushed_release
run_test "reconciles a PR created despite gh failure" test_pr_failure_reconciles_created_pr
run_test "does not reconcile a failed creation with a fork PR" test_fork_release_pr_does_not_reconcile_failed_creation
run_test "prints edit recovery when PR reconciliation fails" test_pr_reconciliation_prints_edit_recovery

if (( TEST_FAILURES > 0 )); then
    printf '\n%d prepare-release test(s) failed\n' "$TEST_FAILURES" >&2
    exit 1
fi

printf '\nAll prepare-release tests passed\n'
