name: Run Danger
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - ".swiftlint.yml"
      - "Dangerfile.swift"
      - "Sources/**"
      - "Tests/**"
      - "Package.swift"
      - "Package.resolved"

jobs:
  build:
    if: github.event.pull_request.draft == false
    name: Run Danger
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Git checkout
        uses: actions/checkout@v7

      - name: Danger
        uses: 417-72KI/danger-swiftlint@v6.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
