name: Tests

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review

jobs:
  unit_tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: .build
          
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
          

      - name: Build
        run: swift build -v

      - name: Run tests
        run: swift test -v

      - name: Run release script tests
        run: /bin/bash scripts/tests/prepare-release-tests.sh
